[2023-02-23 20:28:01,077] {scheduler_job.py:182} INFO - Started process (PID=5062) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:01,077] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:28:01,078] {logging_mixin.py:104} INFO - [2023-02-23 20:28:01,078] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:01,081] {logging_mixin.py:104} INFO - [2023-02-23 20:28:01,080] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:28:01,081] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:01,095] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:28:31,310] {scheduler_job.py:182} INFO - Started process (PID=5121) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:31,311] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:28:31,311] {logging_mixin.py:104} INFO - [2023-02-23 20:28:31,311] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:31,313] {logging_mixin.py:104} INFO - [2023-02-23 20:28:31,313] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:28:31,313] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:28:31,327] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:29:01,396] {scheduler_job.py:182} INFO - Started process (PID=5168) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:01,397] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:29:01,397] {logging_mixin.py:104} INFO - [2023-02-23 20:29:01,397] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:01,399] {logging_mixin.py:104} INFO - [2023-02-23 20:29:01,399] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:29:01,400] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:01,413] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:29:31,884] {scheduler_job.py:182} INFO - Started process (PID=5230) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:31,885] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:29:31,885] {logging_mixin.py:104} INFO - [2023-02-23 20:29:31,885] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:31,888] {logging_mixin.py:104} INFO - [2023-02-23 20:29:31,887] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:29:31,888] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:29:31,920] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.039 seconds
[2023-02-23 20:30:02,691] {scheduler_job.py:182} INFO - Started process (PID=5283) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:02,692] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:30:02,692] {logging_mixin.py:104} INFO - [2023-02-23 20:30:02,692] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:02,695] {logging_mixin.py:104} INFO - [2023-02-23 20:30:02,694] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:30:02,695] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:02,709] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:30:33,107] {scheduler_job.py:182} INFO - Started process (PID=5345) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:33,109] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:30:33,109] {logging_mixin.py:104} INFO - [2023-02-23 20:30:33,109] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:33,111] {logging_mixin.py:104} INFO - [2023-02-23 20:30:33,110] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:30:33,111] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:30:33,124] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:31:03,482] {scheduler_job.py:182} INFO - Started process (PID=5397) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:03,483] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:31:03,484] {logging_mixin.py:104} INFO - [2023-02-23 20:31:03,484] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:03,486] {logging_mixin.py:104} INFO - [2023-02-23 20:31:03,485] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:31:03,486] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:03,500] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:31:33,841] {scheduler_job.py:182} INFO - Started process (PID=5459) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:33,842] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:31:33,842] {logging_mixin.py:104} INFO - [2023-02-23 20:31:33,842] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:33,844] {logging_mixin.py:104} INFO - [2023-02-23 20:31:33,844] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:31:33,845] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:31:33,857] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-23 20:32:04,051] {scheduler_job.py:182} INFO - Started process (PID=5511) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:04,052] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:32:04,052] {logging_mixin.py:104} INFO - [2023-02-23 20:32:04,052] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:04,054] {logging_mixin.py:104} INFO - [2023-02-23 20:32:04,053] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:32:04,054] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:04,069] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:32:34,412] {scheduler_job.py:182} INFO - Started process (PID=5573) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:34,413] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:32:34,414] {logging_mixin.py:104} INFO - [2023-02-23 20:32:34,413] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:34,416] {logging_mixin.py:104} INFO - [2023-02-23 20:32:34,415] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:32:34,416] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:32:34,432] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:33:04,840] {scheduler_job.py:182} INFO - Started process (PID=5634) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:04,840] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:33:04,841] {logging_mixin.py:104} INFO - [2023-02-23 20:33:04,841] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:04,843] {logging_mixin.py:104} INFO - [2023-02-23 20:33:04,842] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:33:04,843] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:04,856] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:33:35,490] {scheduler_job.py:182} INFO - Started process (PID=5687) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:35,491] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:33:35,491] {logging_mixin.py:104} INFO - [2023-02-23 20:33:35,491] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:35,493] {logging_mixin.py:104} INFO - [2023-02-23 20:33:35,493] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:33:35,493] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:33:35,507] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:34:05,908] {scheduler_job.py:182} INFO - Started process (PID=5739) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:05,908] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:34:05,909] {logging_mixin.py:104} INFO - [2023-02-23 20:34:05,909] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:05,911] {logging_mixin.py:104} INFO - [2023-02-23 20:34:05,910] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:34:05,912] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:05,928] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:34:36,266] {scheduler_job.py:182} INFO - Started process (PID=5801) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:36,267] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:34:36,267] {logging_mixin.py:104} INFO - [2023-02-23 20:34:36,267] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:36,270] {logging_mixin.py:104} INFO - [2023-02-23 20:34:36,269] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:34:36,270] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:34:36,286] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 20:35:06,541] {scheduler_job.py:182} INFO - Started process (PID=5853) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:06,543] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:35:06,543] {logging_mixin.py:104} INFO - [2023-02-23 20:35:06,543] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:06,545] {logging_mixin.py:104} INFO - [2023-02-23 20:35:06,545] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:35:06,546] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:06,561] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:35:37,243] {scheduler_job.py:182} INFO - Started process (PID=5915) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:37,243] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:35:37,244] {logging_mixin.py:104} INFO - [2023-02-23 20:35:37,244] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:37,246] {logging_mixin.py:104} INFO - [2023-02-23 20:35:37,245] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:35:37,246] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:35:37,259] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-23 20:36:07,714] {scheduler_job.py:182} INFO - Started process (PID=5976) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:07,715] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:36:07,716] {logging_mixin.py:104} INFO - [2023-02-23 20:36:07,716] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:07,719] {logging_mixin.py:104} INFO - [2023-02-23 20:36:07,718] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:36:07,720] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:07,737] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-23 20:36:22,084] {scheduler_job.py:182} INFO - Started process (PID=5996) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:22,085] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:36:22,085] {logging_mixin.py:104} INFO - [2023-02-23 20:36:22,085] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:22,088] {logging_mixin.py:104} INFO - [2023-02-23 20:36:22,087] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.hooks.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:36:22,088] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:22,102] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:36:53,084] {scheduler_job.py:182} INFO - Started process (PID=6048) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:53,085] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:36:53,085] {logging_mixin.py:104} INFO - [2023-02-23 20:36:53,085] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:53,087] {logging_mixin.py:104} INFO - [2023-02-23 20:36:53,087] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.hooks.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:36:53,087] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:36:53,102] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:37:23,742] {scheduler_job.py:182} INFO - Started process (PID=6110) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:23,743] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:37:23,743] {logging_mixin.py:104} INFO - [2023-02-23 20:37:23,743] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:23,745] {logging_mixin.py:104} INFO - [2023-02-23 20:37:23,744] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.hooks.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:37:23,745] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:23,757] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.017 seconds
[2023-02-23 20:37:29,788] {scheduler_job.py:182} INFO - Started process (PID=6111) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:29,789] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:37:29,789] {logging_mixin.py:104} INFO - [2023-02-23 20:37:29,789] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:29,792] {logging_mixin.py:104} INFO - [2023-02-23 20:37:29,791] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:37:29,792] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:29,806] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:37:44,100] {scheduler_job.py:182} INFO - Started process (PID=6162) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:44,101] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:37:44,101] {logging_mixin.py:104} INFO - [2023-02-23 20:37:44,101] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:44,103] {logging_mixin.py:104} INFO - [2023-02-23 20:37:44,103] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:37:44,104] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:37:44,116] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:38:14,899] {scheduler_job.py:182} INFO - Started process (PID=6215) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:14,900] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:38:14,901] {logging_mixin.py:104} INFO - [2023-02-23 20:38:14,901] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:14,903] {logging_mixin.py:104} INFO - [2023-02-23 20:38:14,902] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:38:14,903] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:14,917] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:38:45,460] {scheduler_job.py:182} INFO - Started process (PID=6276) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:45,461] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:38:45,461] {logging_mixin.py:104} INFO - [2023-02-23 20:38:45,461] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:45,463] {logging_mixin.py:104} INFO - [2023-02-23 20:38:45,462] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:38:45,463] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:38:45,476] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:39:15,855] {scheduler_job.py:182} INFO - Started process (PID=6329) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:15,855] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:39:15,856] {logging_mixin.py:104} INFO - [2023-02-23 20:39:15,856] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:15,858] {logging_mixin.py:104} INFO - [2023-02-23 20:39:15,857] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:39:15,858] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:15,871] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:39:46,379] {scheduler_job.py:182} INFO - Started process (PID=6391) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:46,380] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:39:46,380] {logging_mixin.py:104} INFO - [2023-02-23 20:39:46,380] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:46,382] {logging_mixin.py:104} INFO - [2023-02-23 20:39:46,381] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:39:46,382] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:39:46,395] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-23 20:40:16,921] {scheduler_job.py:182} INFO - Started process (PID=6443) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:16,922] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:40:16,922] {logging_mixin.py:104} INFO - [2023-02-23 20:40:16,922] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:16,924] {logging_mixin.py:104} INFO - [2023-02-23 20:40:16,924] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:40:16,924] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:16,939] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 20:40:47,291] {scheduler_job.py:182} INFO - Started process (PID=6504) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:47,292] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:40:47,292] {logging_mixin.py:104} INFO - [2023-02-23 20:40:47,292] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:47,294] {logging_mixin.py:104} INFO - [2023-02-23 20:40:47,293] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:40:47,294] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:40:47,307] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:41:17,514] {scheduler_job.py:182} INFO - Started process (PID=6557) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:17,515] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:41:17,515] {logging_mixin.py:104} INFO - [2023-02-23 20:41:17,515] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:17,517] {logging_mixin.py:104} INFO - [2023-02-23 20:41:17,517] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:41:17,517] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:17,531] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:41:47,819] {scheduler_job.py:182} INFO - Started process (PID=6619) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:47,819] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:41:47,820] {logging_mixin.py:104} INFO - [2023-02-23 20:41:47,820] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:47,822] {logging_mixin.py:104} INFO - [2023-02-23 20:41:47,821] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:41:47,822] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:41:47,836] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:42:17,891] {scheduler_job.py:182} INFO - Started process (PID=6671) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:17,892] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:42:17,892] {logging_mixin.py:104} INFO - [2023-02-23 20:42:17,892] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:17,894] {logging_mixin.py:104} INFO - [2023-02-23 20:42:17,894] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:42:17,895] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:17,911] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 20:42:48,272] {scheduler_job.py:182} INFO - Started process (PID=6732) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:48,272] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:42:48,273] {logging_mixin.py:104} INFO - [2023-02-23 20:42:48,273] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:48,275] {logging_mixin.py:104} INFO - [2023-02-23 20:42:48,274] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:42:48,275] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:42:48,291] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:43:19,197] {scheduler_job.py:182} INFO - Started process (PID=6784) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:19,198] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:43:19,199] {logging_mixin.py:104} INFO - [2023-02-23 20:43:19,199] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:19,201] {logging_mixin.py:104} INFO - [2023-02-23 20:43:19,200] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:43:19,201] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:19,216] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 20:43:49,484] {scheduler_job.py:182} INFO - Started process (PID=6836) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:49,485] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:43:49,485] {logging_mixin.py:104} INFO - [2023-02-23 20:43:49,485] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:49,487] {logging_mixin.py:104} INFO - [2023-02-23 20:43:49,487] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:43:49,488] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:43:49,501] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:44:19,983] {scheduler_job.py:182} INFO - Started process (PID=6898) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:19,984] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:44:19,984] {logging_mixin.py:104} INFO - [2023-02-23 20:44:19,984] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:19,986] {logging_mixin.py:104} INFO - [2023-02-23 20:44:19,985] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:44:19,986] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:20,004] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-23 20:44:50,965] {scheduler_job.py:182} INFO - Started process (PID=6950) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:50,966] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:44:50,966] {logging_mixin.py:104} INFO - [2023-02-23 20:44:50,966] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:50,968] {logging_mixin.py:104} INFO - [2023-02-23 20:44:50,968] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:44:50,969] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:44:50,983] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 20:45:21,699] {scheduler_job.py:182} INFO - Started process (PID=7012) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:21,700] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:45:21,701] {logging_mixin.py:104} INFO - [2023-02-23 20:45:21,701] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:21,703] {logging_mixin.py:104} INFO - [2023-02-23 20:45:21,702] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:45:21,703] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:21,716] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:45:52,257] {scheduler_job.py:182} INFO - Started process (PID=7071) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:52,258] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:45:52,259] {logging_mixin.py:104} INFO - [2023-02-23 20:45:52,258] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:52,260] {logging_mixin.py:104} INFO - [2023-02-23 20:45:52,260] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:45:52,261] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:45:52,277] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:46:22,956] {scheduler_job.py:182} INFO - Started process (PID=7126) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:22,956] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:46:22,957] {logging_mixin.py:104} INFO - [2023-02-23 20:46:22,957] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:22,959] {logging_mixin.py:104} INFO - [2023-02-23 20:46:22,958] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:46:22,959] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:22,972] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-23 20:46:53,313] {scheduler_job.py:182} INFO - Started process (PID=7178) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:53,314] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:46:53,314] {logging_mixin.py:104} INFO - [2023-02-23 20:46:53,314] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:53,316] {logging_mixin.py:104} INFO - [2023-02-23 20:46:53,316] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:46:53,317] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:46:53,330] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-23 20:47:23,638] {scheduler_job.py:182} INFO - Started process (PID=7240) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:23,639] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:47:23,639] {logging_mixin.py:104} INFO - [2023-02-23 20:47:23,639] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:23,642] {logging_mixin.py:104} INFO - [2023-02-23 20:47:23,641] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:47:23,642] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:23,657] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-23 20:47:53,760] {scheduler_job.py:182} INFO - Started process (PID=7291) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:53,761] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:47:53,761] {logging_mixin.py:104} INFO - [2023-02-23 20:47:53,761] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:53,764] {logging_mixin.py:104} INFO - [2023-02-23 20:47:53,762] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:47:53,764] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:47:53,780] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:48:24,133] {scheduler_job.py:182} INFO - Started process (PID=7353) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:24,134] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:48:24,134] {logging_mixin.py:104} INFO - [2023-02-23 20:48:24,134] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:24,137] {logging_mixin.py:104} INFO - [2023-02-23 20:48:24,136] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:48:24,137] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:24,153] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-23 20:48:54,575] {scheduler_job.py:182} INFO - Started process (PID=7415) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:54,575] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:48:54,576] {logging_mixin.py:104} INFO - [2023-02-23 20:48:54,576] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:54,578] {logging_mixin.py:104} INFO - [2023-02-23 20:48:54,577] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:48:54,578] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:48:54,592] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:49:24,885] {scheduler_job.py:182} INFO - Started process (PID=7467) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:24,886] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:49:24,886] {logging_mixin.py:104} INFO - [2023-02-23 20:49:24,886] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:24,888] {logging_mixin.py:104} INFO - [2023-02-23 20:49:24,888] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:49:24,888] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:24,901] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-23 20:49:55,070] {scheduler_job.py:182} INFO - Started process (PID=7529) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:55,071] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:49:55,071] {logging_mixin.py:104} INFO - [2023-02-23 20:49:55,071] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:55,074] {logging_mixin.py:104} INFO - [2023-02-23 20:49:55,073] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:49:55,074] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:49:55,088] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-23 20:50:25,536] {scheduler_job.py:182} INFO - Started process (PID=7581) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:50:25,538] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 20:50:25,538] {logging_mixin.py:104} INFO - [2023-02-23 20:50:25,538] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:50:25,540] {logging_mixin.py:104} INFO - [2023-02-23 20:50:25,540] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 20:50:25,541] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 20:50:25,575] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.041 seconds
[2023-02-23 21:01:03,664] {scheduler_job.py:182} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:03,665] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:01:03,665] {logging_mixin.py:104} INFO - [2023-02-23 21:01:03,665] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:03,669] {logging_mixin.py:104} INFO - [2023-02-23 21:01:03,667] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 21:01:03,669] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:03,804] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.143 seconds
[2023-02-23 21:01:34,854] {scheduler_job.py:182} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:34,856] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:01:34,857] {logging_mixin.py:104} INFO - [2023-02-23 21:01:34,857] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:34,861] {logging_mixin.py:104} INFO - [2023-02-23 21:01:34,860] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 21:01:34,862] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:01:34,972] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.123 seconds
[2023-02-23 21:02:05,247] {scheduler_job.py:182} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:05,248] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:02:05,249] {logging_mixin.py:104} INFO - [2023-02-23 21:02:05,249] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:05,251] {logging_mixin.py:104} INFO - [2023-02-23 21:02:05,251] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 21:02:05,252] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:05,282] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.037 seconds
[2023-02-23 21:02:35,544] {scheduler_job.py:182} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:35,545] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:02:35,546] {logging_mixin.py:104} INFO - [2023-02-23 21:02:35,546] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:35,548] {logging_mixin.py:104} INFO - [2023-02-23 21:02:35,548] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 21:02:35,549] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:02:35,578] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.036 seconds
[2023-02-23 21:03:05,847] {scheduler_job.py:182} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:03:05,847] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:03:05,848] {logging_mixin.py:104} INFO - [2023-02-23 21:03:05,848] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:03:05,850] {logging_mixin.py:104} INFO - [2023-02-23 21:03:05,849] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 4, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-23 21:03:05,850] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:03:05,878] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.034 seconds
[2023-02-23 21:05:36,278] {scheduler_job.py:182} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:05:36,279] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:05:36,279] {logging_mixin.py:104} INFO - [2023-02-23 21:05:36,279] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:05:36,371] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:05:44,265] {logging_mixin.py:104} INFO - [2023-02-23 21:05:44,265] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:05:44,274] {logging_mixin.py:104} INFO - [2023-02-23 21:05:44,273] {dag.py:1852} INFO - Creating ORM DAG for trigger_airbyte_dbt_job
[2023-02-23 21:05:44,282] {logging_mixin.py:104} INFO - [2023-02-23 21:05:44,281] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:05:44,314] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 8.039 seconds
[2023-02-23 21:06:14,950] {scheduler_job.py:182} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:14,951] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:06:14,951] {logging_mixin.py:104} INFO - [2023-02-23 21:06:14,951] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:14,985] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:14,995] {logging_mixin.py:104} INFO - [2023-02-23 21:06:14,994] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:06:15,015] {logging_mixin.py:104} INFO - [2023-02-23 21:06:15,014] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:06:15,033] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.086 seconds
[2023-02-23 21:06:45,695] {scheduler_job.py:182} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:45,696] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:06:45,697] {logging_mixin.py:104} INFO - [2023-02-23 21:06:45,697] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:45,731] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:06:45,742] {logging_mixin.py:104} INFO - [2023-02-23 21:06:45,742] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:06:45,761] {logging_mixin.py:104} INFO - [2023-02-23 21:06:45,761] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:06:45,796] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.104 seconds
[2023-02-23 21:07:16,645] {scheduler_job.py:182} INFO - Started process (PID=301) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:16,646] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:07:16,647] {logging_mixin.py:104} INFO - [2023-02-23 21:07:16,647] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:16,685] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:16,693] {logging_mixin.py:104} INFO - [2023-02-23 21:07:16,693] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:07:16,708] {logging_mixin.py:104} INFO - [2023-02-23 21:07:16,708] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:07:16,726] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.083 seconds
[2023-02-23 21:07:47,395] {scheduler_job.py:182} INFO - Started process (PID=363) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:47,397] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:07:47,397] {logging_mixin.py:104} INFO - [2023-02-23 21:07:47,397] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:47,425] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:07:47,433] {logging_mixin.py:104} INFO - [2023-02-23 21:07:47,433] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:07:47,449] {logging_mixin.py:104} INFO - [2023-02-23 21:07:47,449] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:07:47,466] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.073 seconds
[2023-02-23 21:08:18,103] {scheduler_job.py:182} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:18,104] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:08:18,104] {logging_mixin.py:104} INFO - [2023-02-23 21:08:18,104] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:18,134] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:18,143] {logging_mixin.py:104} INFO - [2023-02-23 21:08:18,142] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:08:18,159] {logging_mixin.py:104} INFO - [2023-02-23 21:08:18,158] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:08:18,175] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.074 seconds
[2023-02-23 21:08:48,695] {scheduler_job.py:182} INFO - Started process (PID=478) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:48,695] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:08:48,696] {logging_mixin.py:104} INFO - [2023-02-23 21:08:48,696] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:48,725] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:08:48,740] {logging_mixin.py:104} INFO - [2023-02-23 21:08:48,740] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:08:48,756] {logging_mixin.py:104} INFO - [2023-02-23 21:08:48,756] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:08:48,779] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.087 seconds
[2023-02-23 21:09:19,506] {scheduler_job.py:182} INFO - Started process (PID=530) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:19,507] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:09:19,507] {logging_mixin.py:104} INFO - [2023-02-23 21:09:19,507] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:19,542] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:19,551] {logging_mixin.py:104} INFO - [2023-02-23 21:09:19,551] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:09:19,568] {logging_mixin.py:104} INFO - [2023-02-23 21:09:19,568] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:09:19,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.084 seconds
[2023-02-23 21:09:50,428] {scheduler_job.py:182} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:50,429] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:09:50,429] {logging_mixin.py:104} INFO - [2023-02-23 21:09:50,429] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:50,458] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:09:50,466] {logging_mixin.py:104} INFO - [2023-02-23 21:09:50,466] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:09:50,481] {logging_mixin.py:104} INFO - [2023-02-23 21:09:50,481] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:09:50,501] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.075 seconds
[2023-02-23 21:10:21,268] {scheduler_job.py:182} INFO - Started process (PID=654) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:21,269] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:10:21,270] {logging_mixin.py:104} INFO - [2023-02-23 21:10:21,270] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:21,306] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:21,316] {logging_mixin.py:104} INFO - [2023-02-23 21:10:21,315] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:10:21,333] {logging_mixin.py:104} INFO - [2023-02-23 21:10:21,333] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:10:21,369] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.104 seconds
[2023-02-23 21:10:52,212] {scheduler_job.py:182} INFO - Started process (PID=706) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:52,212] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:10:52,213] {logging_mixin.py:104} INFO - [2023-02-23 21:10:52,213] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:52,242] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:10:52,251] {logging_mixin.py:104} INFO - [2023-02-23 21:10:52,251] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:10:52,267] {logging_mixin.py:104} INFO - [2023-02-23 21:10:52,267] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:10:52,290] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.081 seconds
[2023-02-23 21:11:23,207] {scheduler_job.py:182} INFO - Started process (PID=768) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:23,208] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:11:23,209] {logging_mixin.py:104} INFO - [2023-02-23 21:11:23,209] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:23,241] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:23,249] {logging_mixin.py:104} INFO - [2023-02-23 21:11:23,249] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:11:23,266] {logging_mixin.py:104} INFO - [2023-02-23 21:11:23,266] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:11:23,286] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.081 seconds
[2023-02-23 21:11:54,212] {scheduler_job.py:182} INFO - Started process (PID=820) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:54,212] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:11:54,213] {logging_mixin.py:104} INFO - [2023-02-23 21:11:54,213] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:54,242] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:11:54,250] {logging_mixin.py:104} INFO - [2023-02-23 21:11:54,250] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:11:54,264] {logging_mixin.py:104} INFO - [2023-02-23 21:11:54,264] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:11:54,281] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.072 seconds
[2023-02-23 21:12:24,783] {scheduler_job.py:182} INFO - Started process (PID=882) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:24,784] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:12:24,785] {logging_mixin.py:104} INFO - [2023-02-23 21:12:24,785] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:24,867] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:24,949] {logging_mixin.py:104} INFO - [2023-02-23 21:12:24,949] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:12:24,964] {logging_mixin.py:104} INFO - [2023-02-23 21:12:24,964] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:12:24,983] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.203 seconds
[2023-02-23 21:12:55,335] {scheduler_job.py:182} INFO - Started process (PID=934) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:55,336] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-23 21:12:55,336] {logging_mixin.py:104} INFO - [2023-02-23 21:12:55,336] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:55,365] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['trigger_airbyte_dbt_job']) retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-23 21:12:55,375] {logging_mixin.py:104} INFO - [2023-02-23 21:12:55,375] {dag.py:1833} INFO - Sync 1 DAGs
[2023-02-23 21:12:55,391] {logging_mixin.py:104} INFO - [2023-02-23 21:12:55,390] {dag.py:2306} INFO - Setting next_dagrun for trigger_airbyte_dbt_job to 2023-02-22 00:00:00+00:00
[2023-02-23 21:12:55,409] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.077 seconds
